// Mock data for development when Supabase is not available
export const mockFacilities = [
  {
    id: 1,
    name: "New Hope Recovery Center",
    city: "San Francisco",
    state: "CA",
    zip: "94102",
    phone: "(415) 555-0123",
    address: "123 Recovery Lane",
    website: "https://newhoperecovery.com",
    latitude: 37.7749,
    longitude: -122.4194,
    residentialServices: "Long-term residential; Short-term residential; Detoxification",
    allServices: "Substance abuse treatment; Mental health services; Medication-assisted treatment",
    description: "New Hope Recovery Center offers comprehensive residential treatment programs for individuals struggling with substance abuse and co-occurring mental health disorders.",
    capacity: "45 beds",
    amenities: ["24/7 medical supervision", "Individual counseling", "Group therapy", "Family programs", "Recreational activities"],
    acceptedInsurance: ["Medicare", "Medicaid", "Private Insurance", "Self-Pay"],
    programs: ["30-day program", "60-day program", "90-day program", "Extended care"],
    distance: 2.3,
    verified: true,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 2,
    name: "Serenity Hills Treatment Facility",
    city: "San Jose",
    state: "CA", 
    zip: "95112",
    phone: "(408) 555-0456",
    address: "456 Peaceful Way",
    website: "https://serenityhills.org",
    latitude: 37.3382,
    longitude: -121.8863,
    residentialServices: "Long-term residential; Transitional housing",
    allServices: "Substance abuse treatment; Dual diagnosis; Family therapy; Aftercare planning",
    description: "Serenity Hills provides a tranquil environment for long-term recovery with evidence-based treatment approaches.",
    capacity: "32 beds",
    amenities: ["Meditation garden", "Fitness center", "Art therapy", "Nutritional counseling", "Pet therapy"],
    acceptedInsurance: ["Private Insurance", "Self-Pay", "Sliding Scale"],
    programs: ["90-day program", "6-month program", "Alumni program"],
    distance: 12.7,
    verified: true,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 3,
    name: "Golden Gate Recovery Services",
    city: "Oakland",
    state: "CA",
    zip: "94607",
    phone: "(510) 555-0789",
    address: "789 Hope Street",
    website: "https://ggrecovery.net",
    latitude: 37.8044,
    longitude: -122.2712,
    residentialServices: "Short-term residential; Intensive outpatient",
    allServices: "Detoxification; Substance abuse treatment; Mental health services; Case management",
    description: "Golden Gate Recovery Services offers comprehensive treatment programs with a focus on holistic healing and community support.",
    capacity: "28 beds", 
    amenities: ["Medical detox", "Individual therapy", "Group counseling", "Life skills training", "Job placement assistance"],
    acceptedInsurance: ["Medicare", "Medicaid", "Private Insurance", "Payment Assistance"],
    programs: ["Medical detox", "30-day residential", "Intensive outpatient", "Sober living referrals"],
    distance: 8.1,
    verified: true,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 4,
    name: "Pacific Coast Treatment Center",
    city: "Santa Cruz",
    state: "CA",
    zip: "95060",
    phone: "(831) 555-0321",
    address: "321 Ocean View Drive",
    website: "https://pacificcoasttreatment.com",
    latitude: 36.9741,
    longitude: -122.0308,
    residentialServices: "Long-term residential; Sober living",
    allServices: "Substance abuse treatment; Trauma therapy; Family counseling; Relapse prevention",
    description: "Located near the beautiful Pacific Coast, our facility offers a serene environment for recovery with ocean views and nature-based therapy.",
    capacity: "38 beds",
    amenities: ["Ocean views", "Nature trails", "Yoga studio", "Organic garden", "Beach therapy"],
    acceptedInsurance: ["Private Insurance", "Self-Pay", "Scholarships Available"],
    programs: ["60-day program", "90-day program", "Extended residential", "Alumni support"],
    distance: 18.4,
    verified: true,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 5,
    name: "Bay Area Wellness Center",
    city: "Fremont",
    state: "CA",
    zip: "94538",
    phone: "(510) 555-0654",
    address: "654 Wellness Boulevard",
    website: "https://bayareawellness.org",
    latitude: 37.5483,
    longitude: -121.9886,
    residentialServices: "Short-term residential; Transitional housing; Intensive outpatient",
    allServices: "Dual diagnosis; Medication management; Cognitive behavioral therapy; Mindfulness training",
    description: "Bay Area Wellness Center specializes in treating co-occurring disorders with integrated mental health and substance abuse services.",
    capacity: "50 beds",
    amenities: ["Dual diagnosis specialists", "Mindfulness center", "Computer lab", "Educational programs", "Vocational training"],
    acceptedInsurance: ["Medicare", "Medicaid", "Private Insurance", "Self-Pay", "Sliding Scale"],
    programs: ["Dual diagnosis track", "Young adult program", "Professional program", "Continuing care"],
    distance: 25.2,
    verified: true,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 6,
    name: "Redwood Recovery Lodge",
    city: "Mill Valley",
    state: "CA",
    zip: "94941",
    phone: "(415) 555-0987",
    address: "987 Redwood Trail",
    website: "https://redwoodrecovery.com",
    latitude: 37.9061,
    longitude: -122.5450,
    residentialServices: "Long-term residential; Extended care",
    allServices: "Substance abuse treatment; Adventure therapy; Equine therapy; Family programs",
    description: "Nestled among towering redwoods, our lodge provides a unique recovery experience combining traditional therapy with nature-based healing.",
    capacity: "24 beds",
    amenities: ["Redwood forest setting", "Hiking trails", "Equine therapy", "Adventure activities", "Organic meals"],
    acceptedInsurance: ["Private Insurance", "Self-Pay", "Payment Plans"],
    programs: ["90-day wilderness program", "6-month extended care", "Adventure therapy track"],
    distance: 14.6,
    verified: true,
    lastUpdated: new Date().toISOString()
  }
]

export const getMockStats = () => ({
  totalFacilities: 1247,
  totalSearches: 5892,
  lastUpdate: new Date().toISOString()
})