# Development overrides for docker-compose
# This file is automatically loaded when using docker-compose without -f flag

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      DEBUG: "true"
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/soberlivings?schema=public&sslmode=disable
      DIRECT_URL: postgresql://postgres:postgres@postgres:5432/soberlivings?schema=public&sslmode=disable
    volumes:
      - ./frontend:/app
      - /app/node_modules
      # Removed /app/.next volume to fix CSS generation
    ports:
      - "3000:3000"
      - "3001:3000"  # Alternative port for API access
      - "9229:9229"  # Node.js debugger
    command: npm run dev
    dns:
      - 1.1.1.1
      - 8.8.8.8
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: soberlivings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    ports:
      - "6379:6379"

  # Development tools
  adminer:
    image: adminer:latest
    container_name: soberlivings-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - soberlivings

  mailhog:
    image: mailhog/mailhog:latest
    container_name: soberlivings-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - soberlivings