/**
 * Mock data for testing ETL pipeline without API access
 */

export const mockFacilities = [
  {
    id: 'mock-001',
    facilityName: 'Sunrise Recovery Center',
    street1: '123 Healing Way',
    city: 'San Francisco',
    state: 'CA',
    zip: '94110',
    phone: '(415) 555-0101',
    website: 'https://sunriserecovery.example.com',
    latitude: '37.7594',
    longitude: '-122.4186',
    services: ['Detox', 'Residential Treatment', 'Outpatient', 'Aftercare'],
    detox: true,
    residential: true,
    outpatient: true,
    telehealth: false,
    insurance: ['Blue Cross', 'Aetna', 'Cigna', 'Medicare'],
    medicaid: false,
    medicare: true,
    privateInsurance: true,
    amenities: ['Private Rooms', 'Fitness Center', 'Meditation Garden'],
    specialties: ['Dual Diagnosis', 'Trauma', 'Veterans'],
    facilityType: 'Residential Treatment Center',
    description: 'Comprehensive addiction treatment center in San Francisco',
    verified: true,
    licenseNumber: 'CA-12345'
  },
  {
    id: 'mock-002',
    facilityName: 'Pacific Coast Recovery',
    street1: '456 Ocean View Blvd',
    city: 'Santa Monica',
    state: 'CA',
    zip: '90401',
    phone: '(310) 555-0202',
    website: 'https://pacificcoast.example.com',
    latitude: '34.0195',
    longitude: '-118.4912',
    services: ['Residential', 'PHP', 'IOP', 'Sober Living'],
    detox: false,
    residential: true,
    outpatient: true,
    telehealth: true,
    insurance: ['United Healthcare', 'Anthem', 'Kaiser'],
    medicaid: true,
    medicare: true,
    privateInsurance: true,
    amenities: ['Ocean Views', 'Pool', 'Yoga Studio', 'Art Therapy'],
    specialties: ['Young Adults', 'LGBTQ+', 'Professionals'],
    facilityType: 'Luxury Rehab',
    description: 'Upscale treatment facility with ocean views',
    verified: true,
    licenseNumber: 'CA-23456'
  },
  {
    id: 'mock-003',
    facilityName: 'Valley Hope Center',
    street1: '789 Mountain Road',
    city: 'Sacramento',
    state: 'CA',
    zip: '95814',
    phone: '(916) 555-0303',
    website: 'https://valleyhope.example.com',
    latitude: '38.5816',
    longitude: '-121.4944',
    services: ['Outpatient', 'IOP', 'Group Therapy', 'Individual Counseling'],
    detox: false,
    residential: false,
    outpatient: true,
    telehealth: true,
    insurance: ['Medi-Cal', 'Medicare', 'Private Pay'],
    medicaid: true,
    medicare: true,
    privateInsurance: false,
    amenities: ['Parking', 'Coffee Bar', 'Community Room'],
    specialties: ['Co-occurring Disorders', 'Family Therapy'],
    facilityType: 'Outpatient Center',
    description: 'Community-based outpatient treatment services',
    verified: false,
    licenseNumber: null
  },
  {
    id: 'mock-004',
    facilityName: 'Desert Springs Recovery',
    street1: '321 Cactus Lane',
    city: 'Palm Desert',
    state: 'CA',
    zip: '92260',
    phone: '(760) 555-0404',
    website: 'https://desertsprings.example.com',
    latitude: '33.7222',
    longitude: '-116.3745',
    services: ['Detox', 'Residential', 'Holistic Treatment'],
    detox: true,
    residential: true,
    outpatient: false,
    telehealth: false,
    insurance: ['Tricare', 'Blue Shield', 'Cigna'],
    medicaid: false,
    medicare: false,
    privateInsurance: true,
    amenities: ['Desert Views', 'Spa', 'Equine Therapy', 'Golf'],
    specialties: ['Executive Treatment', 'Chronic Relapse'],
    facilityType: 'Executive Rehab',
    description: 'Exclusive desert retreat for addiction recovery',
    verified: true,
    licenseNumber: 'CA-34567'
  },
  {
    id: 'mock-005',
    facilityName: 'Bay Area Recovery Services',
    street1: '567 Tech Boulevard',
    city: 'San Jose',
    state: 'CA',
    zip: '95110',
    phone: '(408) 555-0505',
    website: null,
    latitude: '37.3382',
    longitude: '-121.8863',
    services: ['MAT', 'Counseling', 'Case Management'],
    detox: false,
    residential: false,
    outpatient: true,
    telehealth: true,
    insurance: ['Covered California', 'Medi-Cal'],
    medicaid: true,
    medicare: false,
    privateInsurance: false,
    amenities: ['Childcare', 'Transportation Assistance'],
    specialties: ['Medication-Assisted Treatment', 'Pregnant Women'],
    facilityType: 'MAT Clinic',
    description: 'Medication-assisted treatment and counseling services',
    verified: true,
    licenseNumber: 'CA-45678'
  },
  {
    id: 'mock-006',
    facilityName: 'Harmony House',
    street1: '890 Peaceful Way',
    city: 'Berkeley',
    state: 'CA',
    zip: '94704',
    phone: '(510) 555-0606',
    website: 'https://harmonyhouse.example.com',
    latitude: '37.8716',
    longitude: '-122.2727',
    services: ['Sober Living', 'Aftercare', 'Life Skills'],
    detox: false,
    residential: true,
    outpatient: false,
    telehealth: false,
    insurance: [],
    medicaid: false,
    medicare: false,
    privateInsurance: false,
    amenities: ['Shared Kitchen', 'Laundry', 'Meeting Space'],
    specialties: ['Long-term Recovery', 'Transitional Living'],
    facilityType: 'Sober Living',
    description: 'Structured sober living environment',
    verified: false,
    licenseNumber: null
  },
  {
    id: 'mock-007',
    facilityName: 'Coastal Wellness Center',
    street1: '234 Beach Street',
    city: 'Santa Barbara',
    state: 'CA',
    zip: '93101',
    phone: '(805) 555-0707',
    website: 'https://coastalwellness.example.com',
    latitude: '34.4208',
    longitude: '-119.6982',
    services: ['Detox', 'Residential', 'PHP', 'IOP', 'Outpatient'],
    detox: true,
    residential: true,
    outpatient: true,
    telehealth: true,
    insurance: ['Anthem', 'Kaiser', 'Blue Cross', 'Aetna'],
    medicaid: true,
    medicare: true,
    privateInsurance: true,
    amenities: ['Beach Access', 'Gym', 'Library', 'Music Studio'],
    specialties: ['Dual Diagnosis', 'Eating Disorders', 'Process Addictions'],
    facilityType: 'Comprehensive Treatment Center',
    description: 'Full-spectrum addiction and mental health treatment',
    verified: true,
    licenseNumber: 'CA-56789'
  },
  {
    id: 'mock-008',
    facilityName: 'Mountain View Recovery',
    street1: '999 Summit Drive',
    city: 'Lake Tahoe',
    state: 'CA',
    zip: '96161',
    phone: '(530) 555-0808',
    website: 'https://mountainviewrecovery.example.com',
    latitude: '39.0968',
    longitude: '-120.0324',
    services: ['Residential', 'Wilderness Therapy', 'Adventure Therapy'],
    detox: false,
    residential: true,
    outpatient: false,
    telehealth: false,
    insurance: ['Private Pay Only'],
    medicaid: false,
    medicare: false,
    privateInsurance: false,
    amenities: ['Mountain Views', 'Hiking Trails', 'Rock Climbing', 'Ski Access'],
    specialties: ['Young Adults', 'Adventure-Based Recovery'],
    facilityType: 'Wilderness Therapy',
    description: 'Adventure-based residential treatment in the mountains',
    verified: true,
    licenseNumber: 'CA-67890'
  },
  {
    id: 'mock-009',
    facilityName: 'Urban Recovery Solutions',
    street1: '111 Downtown Plaza',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90012',
    phone: '(213) 555-0909',
    website: null,
    latitude: '34.0522',
    longitude: '-118.2437',
    services: ['IOP', 'Evening Programs', 'Weekend Programs'],
    detox: false,
    residential: false,
    outpatient: true,
    telehealth: true,
    insurance: ['Most Insurance Accepted'],
    medicaid: true,
    medicare: true,
    privateInsurance: true,
    amenities: ['Convenient Location', 'Evening Hours', 'Parking'],
    specialties: ['Working Professionals', 'Students'],
    facilityType: 'Intensive Outpatient',
    description: 'Flexible treatment programs for working adults',
    verified: false,
    licenseNumber: null
  },
  {
    id: 'mock-010',
    facilityName: 'Serenity Gardens',
    street1: '555 Tranquil Path',
    city: 'Napa',
    state: 'CA',
    zip: '94558',
    phone: '(707) 555-1010',
    website: 'https://serenitygardens.example.com',
    latitude: '38.2975',
    longitude: '-122.2869',
    services: ['Residential', 'Holistic Treatment', 'Mindfulness Programs'],
    detox: false,
    residential: true,
    outpatient: false,
    telehealth: false,
    insurance: ['Blue Cross', 'Cigna', 'Private Pay'],
    medicaid: false,
    medicare: false,
    privateInsurance: true,
    amenities: ['Vineyard Views', 'Organic Garden', 'Meditation Spaces', 'Farm-to-Table Dining'],
    specialties: ['Mindfulness-Based Recovery', 'Stress Reduction', 'Executive Burnout'],
    facilityType: 'Holistic Treatment Center',
    description: 'Mindfulness and holistic healing in wine country',
    verified: true,
    licenseNumber: 'CA-78901'
  }
];

/**
 * Mock API response generator
 */
export function getMockApiResponse(page: number = 1, limit: number = 100) {
  const start = (page - 1) * limit;
  const end = start + limit;
  const data = mockFacilities.slice(start, end);
  
  return {
    data,
    pagination: {
      page,
      limit,
      total: mockFacilities.length,
      hasNextPage: end < mockFacilities.length,
      hasPrevPage: page > 1
    }
  };
}