# Prometheus configuration for development monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
scrape_configs:
  # Node.js application metrics
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    
  # PostgreSQL exporter (if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
      
  # Redis exporter (if added)  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
      
  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    
  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']